name: 'Satis build - composer repository'
description: 'Build a static composer repository using satis'

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer
      env:
        runner: self-hosted

    - name: 'Set composer auth'
      run: |
        composer config --global --auth github-oauth.github.com ${{ github.token }}
        composer config --global --no-plugins allow-plugins.composer/satis true
      shell: bash

    - name: 'Set Composer Cache Directory Path Output'
      id: get-composer-cache-dir-path
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        echo "$(composer config cache-files-dir)"
      shell: bash
    
    - name: 'Cache Composer Cache Directory'
      id: cache-composer
      uses: actions/cache@v3
      with:
        path: ${{ steps.get-composer-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

    - name: 'Install satis'
      run: |
        composer create-project composer/satis:dev-main
      shell: bash

    - name: 'Build deps'
      run: |
        php bin/satis build
      shell: bash

branding:
  icon: 'download-cloud'
  color: 'gray-dark'