name: 'Satis build - composer repository'
description: 'Build a static composer repository using satis'

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer
        coverage: none
      env:
        runner: self-hosted

    - name: 'Set composer home'
      id: composer-home
      run: |
        echo "folder=$(composer -n config --global home)\n" >> $GITHUB_OUTPUT
      shell: bash

    - name: 'Set composer auth'
      run: |
        mkdir {{ steps.composer-home.outputs.home }}
        echo "{}" > {{ steps.composer-home.outputs.home }}/composer.json
        composer config --global --auth github-oauth.github.com ${{ github.token }}
      shell: bash

    - name: 'Set Composer Cache Directory Path Output'
      id: get-composer-cache-dir-path
      run: |
        cd {{ steps.composer-home.outputs.home }}
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        echo "$(composer config cache-files-dir)"
      shell: bash
    
    - name: 'Cache Composer Cache Directory'
      id: cache-composer
      uses: actions/cache@v3
      with:
        path: ${{ steps.get-composer-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('{{ steps.composer-home.outputs.home }}/composer.lock') }}

    - name: 'Build deps'
      run: |
        composer global config --no-plugins allow-plugins.composer/satis true

        composer g require composer/satis:dev-main --prefer-dist \
          --no-cache --no-progress --no-interaction -o \
          --ignore-platform-reqs

        php {{ steps.composer-home.outputs.home }}/vendor/bin/satis build satis.json -n
      shell: bash

branding:
  icon: 'download-cloud'
  color: 'gray-dark'